version: "3.8"
services:
  app:
    build: .
    container_name: jenzi-notification-server
    restart: always
    ports:
      - "27500:27500"
    networks:
      - abc-local
    environment:
      - AMQP_HOST=amqp://mq

networks:
  abc-local:
    external: true
