version: "3.8"
services:
  app:
    build: .
    container_name: jenzi-notification-server
    restart: always
    ports:
      - "27500:27500"
    networks:
      - pc-local
    environment:
      - AMQP_HOST=amqp://mq
      - AMQP_PORT=5672
      - REDIS_HOST=redis-server
      - REDIS_PORT=6379
networks:
  pc-local:
    external: true
