version: "3.8"
services:
  app:
    build: .
    container_name: jenzi-notification-server
    restart: always
    ports:
      - "27500:27500"
    environment:
      - AMQP_HOST=amqp://localhost
      - AMQP_PORT=5672
      - REDIS_HOST=localhost
      - REDIS_PORT=6379
    network_mode: host
networks:
  pc-local:
    external: true
