version: "3.8"
services:
  app:
    build: .
    container_name: jenzi-notifcation-server
    restart: always
    ports:
      - "27500:27500"
    networks:
      - jenzi-local
    environment:
      - AMQP_HOST=amqp://mq

networks:
  madali-local:
    external: true
